### ISSUE TITLE
hello author！！

### ISSUE THREAD

**Issue by LIAMROOKIE** [nec-research/n3ic-nsdi22#1]
I want to run on tofino's switch, what do I need to do?

**Comment by DavideSanvito** [comment]
Hello, thanks for your interest in our work.
Our compiler generates code for a generic P4 target, not for a specific hardware target as Tofino.
Your starting point should be the README in the https://github.com/nec-research/n3ic-nsdi22/tree/master/NNtoP4 subfolder.
Once you have generated the P4 code, you might have to adapt it to make it run on your target and you can have a look at the NetFPGA target case we discussed in Section 4.2 as an example.
