### ISSUE TITLE
bnn-exec cannot be found！

### ISSUE THREAD

**Issue by Tyler-ytr** [nec-research/n3ic-nsdi22#2]
Hello, author!
In the paper you wrote, "bnn-exec (C version) is available at github"; however the file is not found in this repository. We would like to draw on that file for performance comparison.
Looking forward to your reply!

**Comment by DavideSanvito** [comment]
Hello, thanks for your interest in our work.
Unfortunately the project is not maintained anymore and we would not be able to help with your request.
