### ISSUE TITLE
Flow-level feature inference

### ISSUE THREAD

**Issue by whxq** [nec-research/n3ic-nsdi22#3]
Hello author, in NNtoP4 only inference is performed on a single feature IPV4srcAddr, if I want to use multiple stream level features for stream classification inference, how should the features be handled? Is it possible to perform and return classification results on BMV2 when using multiple features for inference?

**Comment by DavideSanvito** [comment]
Hello, thanks for your interest in our work.
Unfortunately the project is not maintained anymore and we would not be able to provide extensive support for your request.
In principle, you can concatenate multiple header/metadata fields into a single header/metadata field that is then used as input for the BNN.
The handling of flow states to compute the stream-level input features is out of the scope of this project, which focuses on the execution of the BNN inference on the switch/NIC.
Still, you can have a look at the stateful featues of P4 such as counters and registers which allows to maintain state across packets or flows.
